apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-development
spec:
  acme:
    email: geraldobl58@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-development
    solvers:
    - http01:
        ingress:
          class: nginx
