apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ogeraldoluiz
  namespace: development
  labels:
    name: ogeraldoluiz
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-development
spec:
  ingressClassName: nginx
  rules:
    - host: development.ogeraldoluiz.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: ogeraldoluiz
                port:
                  number: 80

  tls:
    - hosts:
      - development.ogeraldoluiz.com
      secretName: tls-cert-development
