apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ogeraldoluiz
  namespace: development
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
  - host: development.ogeraldoluiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ogeraldoluiz
            port:
              number: 80
  tls:
  - hosts:
    - development.ogeraldoluiz.com
    secretName: tls-cert-production
