# ingress-acme-fix.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ogeraldoluiz
  namespace: development
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-development
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: ogeraldoluiz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ogeraldoluiz
            port:
              number: 80
  tls:
  - hosts:
    - ogeraldoluiz.com
    secretName: tls-cert-development
