name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to Production
        uses: ./.github/workflows/deploy.yml
        with:
          environment-name: production
          environment-url: https://ogeraldoluiz.com
          K8S_NAMESPACE: production

  notify-production:
    needs: [deploy-production]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Success - Production
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: '{"text":"✅ *Production* deployed successfully!"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify Failure - Production
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: '{"text":"❌ *Production* deployment failed!"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
