name: CI/CD Pipeline
run-name: Pipeline CI/CD executed by ${{ github.actor }} in ${{ github.run_number }}

on:
  workflow_call:
    inputs:
      environment-name:
        description: 'Environment name'
        required: true
        type: string
      environment-url:
        description: 'Environment URL'
        required: true
        type: string
      K8S_NAMESPACE:
        description: 'Kubernetes Namespace'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy in Kubernetes
    runs-on: ubuntu-latest

    # Environment Variables
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        # Set Context
      - name: Apply Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - name: Update Deployment
        run: |
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/deployment.yaml
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/service.yaml
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/ingress.yaml
          sed -i 's|host: development.ogeraldoluiz.com|host: ${{ inputs.environment-url }}|g' k8s/ingress.yaml
          sed -i 's|https://||g' k8s/ingress.yaml

      - name: Create Namespace if Not Exists
        run: |
          kubectl get namespace ${{ inputs.K8S_NAMESPACE }} || kubectl create namespace ${{ inputs.K8S_NAMESPACE }}

          - name: Install cert-manager if not exists
          run: |
            if ! kubectl get deployment -n cert-manager cert-manager >/dev/null 2>&1; then
              echo "Installing cert-manager..."
              kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.2/cert-manager.yaml
            else
              echo "cert-manager already installed. Skipping installation."
            fi
            kubectl wait --namespace cert-manager --for=condition=Available --timeout=300s deployment/cert-manager

      - name: Configure Let's Encrypt ClusterIssuer if not exists
        run: |
          if ! kubectl get clusterissuer letsencrypt-development >/dev/null 2>&1; then
            echo "Creating ClusterIssuer letsencrypt-development..."
            cat <<EOF | kubectl apply -f -
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt-development
            spec:
              acme:
                server: https://acme-v02.api.letsencrypt.org/directory
                email: your-email@example.com # Substitua pelo seu e-mail real
                privateKeySecretRef:
                  name: letsencrypt-development
                solvers:
                - http01:
                    ingress:
                      class: nginx
            EOF
          else
            echo "ClusterIssuer letsencrypt-development already exists. Skipping."
          fi

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{ inputs.K8S_NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
          images: geraldobl58/ogeraldoluiz:v${{ github.run_number }}
