name: CI/CD Pipeline
run-name: Pipeline CI/CD executed by ${{ github.actor }} in ${{ github.run_number }}

on:
  workflow_call:
    inputs:
      environment-name:
        description: 'Environment name'
        required: true
        type: string
      environment-url:
        description: 'Environment URL'
        required: true
        type: string
      K8S_NAMESPACE:
        description: 'Kubernetes Namespace'
        required: true
        type: string

jobs:
  deploy:
    name: Deploy in Kubernetes
    runs-on: ubuntu-latest

    # Environment Variables
    environment:
      name: ${{ inputs.environment-name }}
      url: ${{ inputs.environment-url }}

    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

        # Set Context
      - name: Apply Kubernetes Context
        uses: azure/k8s-set-context@v4
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_KUBECONFIG }}

      - name: Update Deployment
        run: |
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/deployment.yaml
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/service.yaml
          sed -i 's|namespace: development|namespace: ${{ inputs.K8S_NAMESPACE }}|g' k8s/ingress.yaml
          sed -i 's|host: development.ogeraldoluiz.com|host: ${{ inputs.environment-url }}|g' k8s/ingress.yaml
          sed -i 's|https://||g' k8s/ingress.yaml

      - name: Create Namespace if Not Exists
        run: |
          kubectl get namespace ${{ inputs.K8S_NAMESPACE }} || kubectl create namespace ${{ inputs.K8S_NAMESPACE }}

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v5
        with:
          namespace: ${{ inputs.K8S_NAMESPACE }}
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
            k8s/ingress.yaml
          images: geraldobl58/ogeraldoluiz:v${{ github.run_number }}

      # Configurar identidade do Git
      - name: Configure Git Identity
        run: |
          git config --global user.email "geraldobl58@gmail.com"
          git config --global user.name "Geraldo Luiz"

      # Commit e push de manifest
      # - name: Commit e push de manifest
      #   run: |
      #     if [ -n "$(git status --porcelain k8s/)" ]; then
      #       git add k8s/
      #       git commit -m "deploy: Update deployment to ${{ inputs.environment-name }} - ${{ github.run_number }}"
      #       git push
      #     else
      #       echo "No changes to commit."
      #     fi
